POST http://localhost:3001/app/authenticate
Content-Type: application/json

{
    "email": "enzo2@gmail.com",
    "password": "teste123"
}


###
POST http://localhost:3001/users
Content-Type: application/json

{
    "name": "enzo2",
    "fancyname": "pipo2",
    "email": "enzo2@gmail.com",
    "document": "30987654321",
    "phone": "2799999999",
    "password": "teste123"
}



###
GET http://localhost:3001/users

###
GET http://localhost:3001/users?search=c0bcbb68-60bf-47e7-a948-244ef69ff82c

###
PUT http://localhost:3001/users/e2815187-9140-4863-b122-
Content-Type: application/json

{
    "name": "Enzo Pilantra",
    "fancyname": "Pipito",
    "email": "enzopilantra@gmail.com",
    "document": "10987654321",
    "phone": "7799999999",
    "password": "sache456"
}

###
DELETE  http://localhost:3001/users/c0bcbb68-60bf-47e7-a948-244ef69ff82c
